-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 19:54:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Garden_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Garden_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Garden_shop` DEFAULT CHARACTER SET utf8 ;
USE `Garden_shop` ;

-- -----------------------------------------------------
-- Table `Garden_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Garden_shop`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL COMMENT '0 = Tree\n1 = Flower\n2 = Decor',
  `price` DOUBLE NOT NULL,
  `quality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Garden_shop`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Garden_shop`.`purchases` (
  `idpurchases` INT NOT NULL AUTO_INCREMENT,
  `idtickets` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`idpurchases`),
  INDEX `idtickets_idx` (`idtickets` ASC) VISIBLE,
  INDEX `idproducts_idx` (`idproduct` ASC) VISIBLE,
  CONSTRAINT `idtickets`
    FOREIGN KEY (`idtickets`)
    REFERENCES `Garden_shop`.`tickets` (`idtickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idproducts`
    FOREIGN KEY (`idproduct`)
    REFERENCES `Garden_shop`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Garden_shop`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Garden_shop`.`stock` (
  `idstock` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idstore` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idstock`),
  INDEX `idstore_idx` (`idstore` ASC) VISIBLE,
  INDEX `idproduct_idx` (`idproduct` ASC) VISIBLE,
  CONSTRAINT `idstore`
    FOREIGN KEY (`idstore`)
    REFERENCES `Garden_shop`.`stores` (`idstores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idproduct`
    FOREIGN KEY (`idproduct`)
    REFERENCES `Garden_shop`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Garden_shop`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Garden_shop`.`stores` (
  `idstores` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `current_stock_value` DOUBLE NOT NULL,
  `current_sales_value` DOUBLE NOT NULL,
  PRIMARY KEY (`idstores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Garden_shop`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Garden_shop`.`tickets` (
  `idtickets` INT NOT NULL AUTO_INCREMENT,
  `idstore` INT NOT NULL,
  PRIMARY KEY (`idtickets`),
  INDEX `idstores_idx` (`idstore` ASC) VISIBLE,
  CONSTRAINT `idstores`
    FOREIGN KEY (`idstore`)
    REFERENCES `Garden_shop`.`stores` (`idstores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;